// <auto-generated />
using System;
using International_Voting_Systems;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace International_Voting_Systems.Migrations
{
    [DbContext(typeof(MainDatabaseContext))]
    [Migration("20260208181639_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("International_Voting_Systems.Candidate", b =>
                {
                    b.Property<int>("CandidateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidateAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateConstituency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CandidateDOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateFullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateNationalInsuranceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CandidateID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("International_Voting_Systems.Voter", b =>
                {
                    b.Property<int>("VoterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ContactNumber")
                        .HasColumnType("REAL");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VoterID");

                    b.ToTable("Voters");
                });
#pragma warning restore 612, 618
        }
    }
}
