// <auto-generated />
using System;
using International_Voting_Systems;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace International_Voting_Systems.Migrations
{
    [DbContext(typeof(MainDatabaseContext))]
    [Migration("20260221121030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("International_Voting_Systems.Candidate", b =>
                {
                    b.Property<int>("CandidateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidateAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateConstituency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CandidateDOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateFullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateNationalInsuranceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CandidateID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("International_Voting_Systems.Code", b =>
                {
                    b.Property<int>("CodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OTP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoterID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CodeID");

                    b.HasIndex("VoterID");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("International_Voting_Systems.IDTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoterID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CandidateID");

                    b.HasIndex("CodeID");

                    b.HasIndex("VoterID");

                    b.ToTable("IDs");
                });

            modelBuilder.Entity("International_Voting_Systems.Voter", b =>
                {
                    b.Property<int>("VoterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ContactNumber")
                        .HasColumnType("REAL");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VoterID");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("International_Voting_Systems.Code", b =>
                {
                    b.HasOne("International_Voting_Systems.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("International_Voting_Systems.IDTable", b =>
                {
                    b.HasOne("International_Voting_Systems.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("International_Voting_Systems.Code", "Code")
                        .WithMany()
                        .HasForeignKey("CodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("International_Voting_Systems.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Code");

                    b.Navigation("Voter");
                });
#pragma warning restore 612, 618
        }
    }
}
